### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by OfficialYoungX** [RelaxedJS/ReLaXed#101] opened 2018-06-30 04:59 UTC
### I don't know what happened about this. I've tried your [troubleshooting page](https://github.com/RelaxedJS/ReLaXed/wiki/Troubleshooting).But I still can't install this successfully.
<img width="886" alt="image" src="https://user-images.githubusercontent.com/25839518/42121595-b1d25aec-7c64-11e8-8f75-042c653fbb32.png">

error code:
1858 silly install generateActionsToTake
1859 warn checkPermissions Missing write access to /usr/local/lib/node_modules
1860 timing stage:rollbackFailedOptional Completed in 0ms
1861 timing stage:runTopLevelLifecycles Completed in 41243ms
1862 verbose stack Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
1863 verbose cwd /Users/mac
1864 verbose Darwin 17.5.0
1865 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "relaxedjs"
1866 verbose node v10.3.0
1867 verbose npm  v6.1.0
1868 error path /usr/local/lib/node_modules
1869 error code EACCES
1870 error errno -13
1871 error syscall access
1872 error Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
1872 error  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
1872 error   stack:
1872 error    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
1872 error   errno: -13,
1872 error   code: 'EACCES',
1872 error   syscall: 'access',
1872 error   path: '/usr/local/lib/node_modules' }
1873 error The operation was rejected by your operating system.
1873 error It is likely you do not have the permissions to access this file as the current user
1873 error
1873 error If you believe this might be a permissions issue, please double-check the
1873 error permissions of the file and its containing directories, or try running
1873 error the command again as root/Administrator (though this is not recommended).
1874 verbose exit [ -13, true ]

**Comment by DanielRuf** [comment] 2018-06-30 09:49
Can you provide more info about your environment and how you installed node and npm (hopefully without sudo)?

Is some antivirus solution installed which blocks this?

**Comment by OfficialYoungX** [comment] 2018-06-30 16:20
### I know that I shoudn't use `sudo`, but I still tried this.
### Here is the error information:

```
➜  ~ sudo npm install -g relaxedjs
Password:
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
/usr/local/bin/pretty-pdf-thumbnail -> /usr/local/lib/node_modules/relaxedjs/src/cli-tools/pretty-pdf-thumbnail.js
/usr/local/bin/relaxed -> /usr/local/lib/node_modules/relaxedjs/src/index.js
/usr/local/bin/pdf2gif -> /usr/local/lib/node_modules/relaxedjs/src/cli-tools/pdf2gif.js

> fsevents@1.2.4 install /usr/local/lib/node_modules/relaxedjs/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/relaxedjs/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.9.0 install /usr/local/lib/node_modules/relaxedjs/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/local/lib/node_modules/relaxedjs/node_modules/node-sass/vendor/darwin-x64-64 : { Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/relaxedjs/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:872:3)
    at sync (/usr/local/lib/node_modules/relaxedjs/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/relaxedjs/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/local/lib/node_modules/relaxedjs/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/relaxedjs/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/usr/local/lib/node_modules/relaxedjs/node_modules/node-sass/vendor' }

> puppeteer@1.5.0 install /usr/local/lib/node_modules/relaxedjs/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r564778! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/relaxedjs/node_modules/puppeteer/.local-chromium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/relaxedjs/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.5.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2018-06-30T16_15_02_376Z-debug.log
```

**Comment by OfficialYoungX** [comment] 2018-07-01 11:15
LoL, I've solved this problem!
This main reason is
* My npm permission has some problem.
* My mac didn't install `Puppeteer`.
Then I install `Puppeteer`manually.And fixed my nom option.
It worded! Whatever, thanks a lot.

**Comment by DanielRuf** [comment] 2018-07-01 11:46
It probably was due to `sudo npm i -g npm`, an uninstall and reinstall would have probably solved this. In general this is an npm issue and not directly related to any of the affected packages. The problem is that npm spawns further processes which have other owners in your case. So this happened and will happen with other projects too.
I recommend opening an issue at https://github.com/npm/npm/issues in this case in the future.

I'll close this issue as this seems to be (partly) solved.

Thanks the update and I'm glad that it works now.

**Closed by DanielRuf** 2018-07-01 11:46 UTC

**Comment by OfficialYoungX** [comment] 2018-07-01 11:52
Yes, thanks for your recommendation.
Relaxedjs words really well now.
